server:
  port: 8082

spring:
  application:
    name: game-service

---

spring:
  profiles: default
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/