server:
  port: 8081

spring:
  application:
    name: scoring-service

---
spring:
  profiles: default
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
logging:
  level: warn
---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/