---
version: '2'
services:
  discovery-service:
    image: discovery-service
    container_name: my-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - single-tier

  game-service:
    image: game-service
    container_name: my-game-service
    ports:
      - "8082:8082"
    hostname: "game-service"
    expose:
      - "8082"
    links:
      - "discovery-service"
    networks:
      - single-tier

  scoring-service:
    image: scoring-service
    container_name: my-scoring-service
    hostname: "scoring-service"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    links:
      - "discovery-service"
    networks:
      - single-tier

networks:
   single-tier:
      driver: bridge