spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0